from aiogram.dispatcher.filters.state import StatesGroup, State


class AdminStates(StatesGroup):
    SEND_MEDIA_TO_USERS = State()
    SEND_TO_USERS = State()
    CANCEL_MESSAGE = State()
    ANSWER_MESSAGE = State()
    CATEGORY = State()
    PAID_LESSONS_ONE = State()
    PAID_LESSONS_TWO = State()
    PAID_LESSONS_THREE = State()
    PAID_LESSONS_FOUR = State()
    PAID_LESSONS_FIVE = State()
    FREE_CATEGORY = State()
    FREE_LESSONS_ONE = State()
    FREE_LESSONS_TWO = State()
    FREE_LESSONS_THREE = State()
    FREE_LESSONS_FOUR = State()
    FREE_LESSONS_FIVE = State()
    EDIT_CATEGORY = State()
    EDIT_CATEGORY_SECOND = State()
    EDIT_LESSON_ONE = State()
    EDIT_LESSON_TWO = State()
    EDIT_LESSON_THREE = State()
    EDIT_LESSON_FOUR = State()
    DELETE_CATEGORY = State()
    DELETE_LESSON_ONE = State()
    DELETE_LESSON_TWO = State()
    DELETE_LESSON_ONE_PAID = State()
    DELETE_LESSON_TWO_PAID = State()
    EDIT_FREE_LESSON_ONE = State()
    EDIT_FREE_LESSON_TWO = State()
    EDIT_FREE_LESSON_THREE = State()
    EDIT_FREE_LESSON_FOUR = State()
